booking:
  property: Booking Profile DEV

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bookingdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true